#!/usr/bin/env python3

# BSD 2-Clause License
#
# Copyright (c) 2017, Tim Sammut with modifications by Ilker Temir
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import base64
import cgi
from http import cookies as Cookie
import json
import onetimepass
import os
import re
import settings
import sys, subprocess
sys.path.append( '/home/user/venv/lib/python3.11/site-packages' )
import time
import urllib
import mysql.connector
from mysql.connector import errorcode
runtime=0
def mysql_conn():

  try:
    global cnx
    cnx = mysql.connector.connect(
    host="127.0.0.1",
    port=3306,
    user="",
    password="",
    database = "", auth_plugin='mysql_native_password')
    return cnx
  except mysql.connector.Error as err:
    print(err)    

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
STATE_DIR = os.path.join(BASE_DIR, 'state')
TEMPLATE_FILE = os.path.join(BASE_DIR, 'template.html')

fields = cgi.FieldStorage()
token_user = fields.getvalue('p', None)
url = os.environ.get('QUERY_STRING', '/')
host = os.environ.get('SERVER_NAME', '/')

user = os.environ.get('REMOTE_USER', None)
user_secret = 'DEFAULT'

cnx = mysql_conn()
cursor = cnx.cursor(buffered=True)

try:

  select_query = ("SELECT the_mfa_secret FROM user WHERE userid = %s LIMIT 1")
  cursor.execute(select_query, (user,)) 
  rows = cursor.fetchall()
  
  for i, row in enumerate(rows):
  
    try:

      user_secret = "" + row[0] + ""        
      
      if user_secret == "none":
      
        raise e
        
    except Exception as e:

      hexsecret_cmd = "head -10 /dev/urandom | md5sum | cut -b 1-30 | xargs oathtool --verbose --totp | grep \"Base32\" | cut -b 16-"
      hexsecret_cmd_proc = subprocess.Popen([hexsecret_cmd], stdout=subprocess.PIPE, shell=True)
      (out, err) = hexsecret_cmd_proc.communicate() 
      hexsecret_cmd_log = out.decode('utf-8')
      hexsecret_cmd_log_err = err
      hexsecret_cmd_log = re.sub("\n", "", hexsecret_cmd_log)

      qrencode_cmd = "/usr/bin/qrencode otpauth://totp/" + user + "?secret=" + hexsecret_cmd_log + " -o /var/www/qrencode/" + hexsecret_cmd_log + ".png"
      qrencode_cmd_proc = subprocess.Popen([qrencode_cmd], stdout=subprocess.PIPE, shell=True)
      (out, err) = qrencode_cmd_proc.communicate() 
      qrencode_cmd_log = out.decode('utf-8')
      qrencode_cmd_log_err = err

      update_query = ("UPDATE user SET the_mfa_secret = %s WHERE userid = %s")
      cursor.execute(update_query, (hexsecret_cmd_log,user))
      cnx.commit()
      
      runtime=1
      print("Content-type: text/html\r\n\r\n")
      print("<center style=\"font-family:verdana\"><h2>Scan this code with your mobile MFA application</h2> Once scanned, submit the code in the form to continue. <P> This QR code will appear for just this one login attempt.<P><img src = /qrencode/" + hexsecret_cmd_log + ".png></div></center>")
            
except Exception as e:  
  cursor.close()
  cnx.close()
cursor.close()
cnx.close()

if onetimepass.valid_totp(token=token_user, secret=user_secret, window=1):
    cookie = Cookie.SimpleCookie()
    # Create a random key and store it in session cookie
    random = os.urandom(80)
    key = re.sub(r'[=+/]+', '', base64.b64encode(random).decode("ascii"))
    cookie['2FA_Auth'] = key
    cookie['2FA_Auth']['path'] = '/'
    cookie['2FA_Auth']['expires'] = settings.EXPIRATION_TIME
    # You need to comment out following two lines if you are using http
    cookie['2FA_Auth']['secure'] = True
    cookie['2FA_Auth']['httponly'] = True

    # Create a local state file with the key value, it will be checked
    # by Apache mod_rewrite
    state_file = os.path.join(STATE_DIR, key)
    with open(state_file, 'w+') as state:
        # Following write is optional, used for logging
        state.write('%s\n%s\n%s\n' % (os.environ.get('HTTP_USER_AGENT', ''),
                os.environ.get('REMOTE_ADDR', ''),
                os.environ.get('REMOTE_USER', '')))
    print("Status: 302 Moved")
    print("Location: /")
    print(cookie)
    print()
else:
  if runtime == 0:
    print("Content-type: text/html\r\n\r\n")    
  print(open(TEMPLATE_FILE).read())
 
